#!/usr/bin/env php
<?php

$currentDir = __DIR__;
require "$currentDir/vendor/autoload.php";

$cli = new Garden\Cli\Cli();

$args = $cli->description('Generate php classes from wsdl document')
    ->arg('url', 'Wsdl document url', true)
    ->opt('namespace:n', 'Namespace to insert at top of file')
    ->opt('classes:c', 'List of classes separated by commas')
    ->parse($argv);

$url = $args->getArg('url');
$onlyClasses = $args->getOpt('classes');
$namespace = $args->getOpt('namespace');

if (preg_match("/^(http|https):\/\/([^?]+)?/", $url, $matches) !== 1) {
    throw new RuntimeException('Unable to parse url');
}

$fileName = str_replace('/', '.', $matches[2]);
$sourceDir = "$currentDir/source/";
$newSourceFileName = $sourceDir . $fileName;

copy($url, $newSourceFileName);

$params = [
    'inputFile' => $newSourceFileName,
    'outputDir' => "$currentDir/output/$fileName",
];

if (!$onlyClasses !== null) {
    $params['classNames'] = $onlyClasses;
    if ($namespace !== null) {
        $params['namespaceName'] = $namespace;
    }
}

$generator = new \Wsdl2PhpGenerator\Generator();
$generator->generate(new \Wsdl2PhpGenerator\Config($params));